version: "3.7"

services:
  mysql8.0:
    container_name: "mysql-v8.0"
    build: ./mysql8.0
    ports:
      - 3307:3306
    networks:
      - databases
    volumes:
      - ./data/mysql8:/var/lib/mysql
      - ./logs/mysql8:/var/log/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_520_ci --default-authentication-plugin=mysql_native_password --innodb_use_native_aio=off
    environment:
      MYSQL_ROOT_PASSWORD: pass

  mysql5.0:
    container_name: "mysql-v5.7"
    build: ./mysql5.7
    ports:
      - 3308:3306
    networks:
      - databases
    volumes:
      - ./data/mysql5:/var/lib/mysql
      - ./logs/mysql5:/var/log/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_520_ci --default-authentication-plugin=mysql_native_password --innodb_use_native_aio=off
    environment:
      MYSQL_ROOT_PASSWORD: pass

networks:
  databases:
    name: mysql-databases
    driver: bridge
